---
# tasks file for 2do_parcial
- debug:
    msg: "Tareas del 2do Parcial"

- name: "Crear directorios en /tmp/multi_Pruebas_borrame/"
  file:
    path: "/tmp/2do_parcial/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "alumno"
    - "equipo"
      
- name: "Agrego archivo desde template"
  template:
    src: alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: "Agrego archivo desde template"
  template:
    src: equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: "add NOPASSWD in sudores for group {{ GROUP_ADMIN }}"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

